name: entitas_ff
authors:
- Maxim Zaks <maxim.zaks@gmail.com>
description: Entitas for Flutter
homepage: https://github.com/mzaks/entitas_ff
version: 0.1.0

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: '>=0.12.24+2 <2.0.0'
  flutter_test:
    sdk: flutter